// models/language_mapping.dart

const Map<String, String> languageMap = {
  'Arabic': 'AR',
  'Chinese (Simplified)': 'ZH-CN',
  'Chinese (Traditional)': 'ZH-TW',
  'English (UK)': 'en-GB',
  'English (US)': 'en-US',
  'French': 'FR',
  'German': 'DE',
  'Greek': 'EL',
  'Hebrew': 'HE',
  'Hindi': 'HI',
  'Indonesian': 'ID',
  'Italian': 'IT',
  'Japanese': 'JA',
  'Korean': 'KO',
  'Malay': 'MS',
  'Portuguese': 'PT',
  'Russian': 'RU',
  'Spanish': 'ES',
  'Swedish': 'SV',
  'Thai': 'TH',
  'Turkish': 'TR',
  'Vietnamese': 'VI',
  'Bengali': 'BN',
  'Czech': 'CS',
  'Danish': 'DA',
  'Hungarian': 'HU',
  'Lithuanian': 'LT',
  'Latvian': 'LV',
  'Norwegian': 'NO',
  'Polish': 'PL',
  'Romanian': 'RO',
  'Slovak': 'SK',
  'Ukrainian': 'UK',
  'Welsh': 'CY',
  'Afrikaans': 'AF',
  'Basque': 'EU',
  'Catalan': 'CA',
  'Esperanto': 'EO',
  'Estonian': 'ET',
  'Finnish': 'FI',
  'Georgian': 'KA',
  'Icelandic': 'IS',
  'Irish': 'GA',
  'Maltese': 'MT',
  'Serbian': 'SR',
  'Albanian': 'SQ',
  'Armenian': 'HY',
  'Azerbaijani': 'AZ',
  'Belarusian': 'BE',
  'Bosnian': 'BS',
  'Bulgarian': 'BG',
  'Croatian': 'HR',
  'Kurdish': 'KU',
  'Macedonian': 'MK',
  'Mongolian': 'MN',
  // Tambahkan bahasa lain sesuai kebutuhan
};
